<?php use Laminas\Form\Element;

$element = new Element\Hidden('my-hidden');
$element->setValue('foo');

?>

<table class="table">
    <tr>
        <th>Valor de de la compra</th>
        <th>Utilidad</th>
        <th>Iva</th>
        <th></th>
    </tr>
    <tr>
            <td><input type="text" id="valor" value="0" onChange="multiplicar();"></td>
            <td><input type="text" id="utilidad" value="0" onChange="multiplicar();"></td>
            <td><input type="text" id="iva" value="0" onChange="multiplicar();"></td>
            <td></td>
        </tr>
    <tr>
        <td>
            Ganancia<input type="text" id="resultado">
        </td>
        <td>
            Valor venta<input type="text" id="resultado2">
        </td>
        <td></td>
    </tr>
</table>

<table class="table">

    <tr>
        <th>1 Banda</th>
        <th><select id="color1" onChange="colores();">

                <option value="0">negro</option>
                <option value="1">cafe</option>
                <option value="2">rojo</option>
                <option value="3">naranja</option>
                <option value="4">amarillo</option>
                <option value="5">verde</option>
                <option value="6">azul</option>
                <option value="7">Violeta </option>
                <option value="8">Gris</option>
                <option value="9">Blanco</option>

            </select></th>
          </tr>
    <tr>
        <td>2 Banda</td>
        <th><select id="color2" onChange="colores();">

                <option value="0">negro</option>
                <option value="1">cafe</option>
                <option value="2">rojo</option>
                <option value="3">naranja</option>
                <option value="4">amarillo</option>
                <option value="5">verde</option>
                <option value="6">azul</option>
                <option value="7">Violeta </option>
                <option value="8">Gris</option>
                <option value="9">Blanco</option>

            </select></th>
           <td></td>
    </tr>
    <tr>
        <td>3 Banda</td>
        <th><select id="color3" onChange="colores();">

                <option value="1">negro</option>
                <option value="10">cafe</option>
                <option value="100">rojo</option>
                <option value="1000">naranja</option>
                <option value="10000">amarillo</option>
                <option value="100000">verde</option>
                <option value="1000000">azul</option>
                <option value="10000000">Violeta </option>
                <option value="100000000">Gris</option>
                <option value="1000000000">Blanco</option>

            </select></th>
                <td></td>
    </tr>
    <tr>
        <td></td>
        <th> Valor de la resistencia <input type="text" id="resultado3"> ohmios</th>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <th></th>
        <td></td>
    </tr>

</table>
