<?php use Laminas\Form\Element;

$element = new Element\Hidden('my-hidden');
$element->setValue('foo');

?>

<table>
  <tr>
      <td> <a class="nav-link" href="<?= $this->url('bd', ['action' => 'index']) ?>">Crear Base de Datos<span class="sr-only"></span></a>
      </td>
    </tr>
    <tr>
        <td> <a class="nav-link" href="<?= $this->url('bd', ['action' => 'index2']) ?>">Crear tabla<span class="sr-only"></span></a></td>
    </tr>

    <tr>
        <td> <a class="nav-link" href="<?= $this->url('bd', ['action' => 'index2']) ?>">Crear backup <span class="sr-only"></span></a></td>
    </tr>
</table>
