<?php

$title = 'Mis productos';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('tienda', ['action' => 'record']) ?>">Nuevo producto</a>
</p>

<form action="<?= $this->url('tienda', ['action' => 'index']) ?>" method="post">
  <div class="form-row align-items-center">
    <div class="col-auto">
      <label class="sr-only" for="inlineFormInputGroup">Buscar por</label>
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">Nombre:</div>
        </div>
        <input type="text" class="form-control" id="texto_buscar" name="texto_buscar" placeholder="Buscar por...">
      </div>
    </div>    
    <div class="col-auto">
      <button type="submit" id="buscar" name="buscar" class="btn btn-primary mb-2">Buscar</button>
    </div>
  </div>
</form>

<table class="table">
    <tr>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Cantidad</th>
        <th>Marca</th>
        <th></th>
    </tr>
    <?php foreach ($productos as $producto) : ?>
        <tr>
            <td><?= $this->escapeHtml($producto->nombre) ?></td>
            <td><?= $this->escapeHtml($producto->precio) ?></td>
            <td><?= $this->escapeHtml($producto->cantidad) ?></td>
            <td><?= $this->escapeHtml($producto->marca) ?></td>
            <td>
                <a href="<?= $this->url('tienda', ['action' => 'record', 'id' => $producto->id]) ?>">Editar</a>
                <a href="<?= $this->url('tienda', ['action' => 'delete', 'id' => $producto->id]) ?>" onclick="return confirm('Confirma eliminar?')">Borrar</a>
            </td>
        </tr>
    <?php endforeach; ?>    
</table>
<a href="<?= $this->url('tienda', ['action' => 'pdf']) ?>" class="btn btn-info"><i class="fa fa-file-pdf-o"></i> Generar PDF</a>
<?php
//$form->setAttribute('action', $this->url('application', ['action' => 'generar']));
?>