<?php

$title = 'Mis productos';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('tienda', ['action' => 'record']) ?>">Nuevo producto</a>
</p>

<table class="table">
    <tr>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Cantidad</th>
        <th></th>
    </tr>
    <?php foreach ($productos as $producto) : ?>
        <tr>
            <td><?= $this->escapeHtml($producto->nombre) ?></td>
            <td><?= $this->escapeHtml($producto->precio) ?></td>
            <td><?= $this->escapeHtml($producto->cantidad) ?></td>
            <td>
                <a href="<?= $this->url('tienda', ['action' => 'record', 'id' => $producto->id]) ?>">Editar</a>
                <a href="<?= $this->url('tienda', ['action' => 'delete', 'id' => $producto->id]) ?>" onclick="return confirm('Confirma eliminar?')">Borrar</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>