<?php
$title = (!$id)?'Agregar nuevo producto':'Editar producto';
$this->headTitle($title);
?>
    <h2><?= $this->escapeHtml($title) ?></h2>
<?php

$nombre = $form->get('nombre');
$nombre->setAttribute('class', 'form-control');
$nombre->setAttribute('placeholder', 'Nombre del producto');


$precio = $form->get('precio');
$precio->setAttribute('class', 'form-control');
$precio->setAttribute('placeholder', 'Precio');


$cantidad = $form->get('cantidad');
$cantidad->setAttribute('class', 'form-control');
$cantidad->setAttribute('placeholder', 'Cantidad');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$params = ['action' => 'record'];

if ($id){
    $params['id'] = $id;
}

$form->setAttribute('action', $this->url('tienda', $params));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($nombre) ?>
        <?= $this->formElement($nombre) ?>
        <?= $this->formElementErrors()->render($nombre, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($precio) ?>
        <?= $this->formElement($precio) ?>
        <?= $this->formElementErrors()->render($precio, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($cantidad) ?>
        <?= $this->formElement($cantidad) ?>
        <?= $this->formElementErrors()->render($cantidad, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();