<table>
    <tr>
        <td><img src="/img/logo.jpg"></td>
    </tr>       
</table>
<br>
<table style="border-style: solid;">
    <thead>
    <tr>
        <td colspan="7"><b><?= $this->tableTittle ?></b></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td style="background-color: #e5dada;">Nombre</td>
        <td style="background-color: #e5dada;">Precio</td>
        <td style="background-color: #e5dada;">Cantidad</td>
        <td style="background-color: #e5dada;">Marca</td>
    </tr>
    <?php foreach ($productos as $producto) : ?>
        <tr>
            <td><?= $this->escapeHtml($producto->nombre) ?></td>
            <td><?= $this->escapeHtml($producto->precio) ?></td>
            <td><?= $this->escapeHtml($producto->cantidad) ?></td>
            <td><?= $this->escapeHtml($producto->marca) ?></td>            
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>