<br><br>
<table style="border-style: solid;">
    <thead>
    <tr>
        <td colspan="7"><b><?= $this->tableTittle ?></b></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td style="background-color: #e5dada;">Nombre</td>
        <td style="background-color: #e5dada;">Precio</td>
        <td style="background-color: #e5dada;">Cantidad</td>
        <td style="background-color: #e5dada;">Marca</td>
    </tr>
    <?= $this->tableContent ?>
    </tbody>
</table>